name: Build and Push Docker Image

on:  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Log in to GitHub Packages
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      env:
        VERSION: ${{ github.sha }}
      run: |
        docker build -t docker.pkg.github.com/${{ github.repository }}/insightiq:${{ env.VERSION }} .
        docker push docker.pkg.github.com/${{ github.repository }}/insightiq:${{ env.VERSION }}
