name: Docker Build and Push

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Build and push Docker image
      env:
        USERNAME: ${{ github.actor }}
        VERSION: ${{ github.sha }}
      run: |
        echo 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 | docker login docker.pkg.github.com -u insightiq --password-stdin
        docker build -t docker.pkg.github.com/insightiq/repository/insightiq:${{ env.VERSION }} .
        docker push docker.pkg.github.com/insightiq/repository/insightiq:${{ env.VERSION }}

 
