name: Docker Build and Push

on: [push, pull_request]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
     - name: Build and Push Docker Image
       run: |
        docker build -t docker.pkg.github.com/username/repository/image:tag .
        echo "${{ secrets.DOCKER_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin
        docker push docker.pkg.github.com/username/repository/image:tag
