name: Built a docker image

#Trigger that start the workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
  workflow_dispatch:


jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
    #Check out the repository code to Ubuntu runner
      - name: Checkout Code
        uses: actions/checkout@v2
    
    #Log in to DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

    #Build and push the image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: 1365890/devops_projects:latest
