name: Python Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Choose your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Replace with your requirements file if needed

    - name: Run unit tests and generate reports
      run: |
        mkdir test-reports  # Create a directory to store test reports
        python -m unittest discover -s ./ -p '*test_app.py'  # Run tests
        
        # Generate your test reports using xmlrunner in the 'test-reports' directory
        python -m xmlrunner discover -s ./ -p '*test_app.py' --output=./test-reports

    - name: Archive test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: test-reports  # Store the test reports directory as an artifact
