name: Python Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Choose your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Replace with your requirements file if needed

    - name: Run unit tests
      run: |
        python -m unittest discover -s ./ -p 'test_app.py'  # Assuming tests are in the root directory

    - name: Archive test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: .  # Store all files in the root directory as artifacts
